import createClient, { Middleware, MiddlewareOnRequest, wrapAsPathBasedClient } from "openapi-fetch";
import { paths } from "./openapi/schema.js"; // generated by openapi-typescript
import { WebhookEventBody } from "./types.js";

// TODO: implement custom type wrapper that has parameters like auth and plugs into this
type HttpMethod = "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace";
interface UnprotectedRoute {
    path: keyof paths,
    method: HttpMethod,
}

export * from './types.js';

function unprotectedRoutes(): UnprotectedRoute[] {
    /*
    script for finding these from schema
    for (const path in paths) {
        const pathObj = paths[path as keyof typeof paths];
        for (const method in pathObj) {
            const operation = pathObj[method as keyof typeof pathObj];
            if (!('security' in operation)) {
                console.log(path, method);
            }
        }
    }
    */
    return [
        {
            path: '/v3/auth',
            method: "post",
        },
        {
            path: '/v3/auth/password/reset',
            method: "post",
        },
        {
            path: '/v3/auth/password/update',
            method: "post",
        },
        {
            path: '/v3/logging',
            method: "post",
        },
    ];
}

export interface TelzioOptions {
    apiKey?: string,
}

type TelzioClient = ReturnType<typeof wrapAsPathBasedClient<paths>>;

export default class Telzio {
    private static readonly _baseUrl = 'https://api.telzio.com';

    private _options: TelzioOptions;
    private _unprotectedRoutes: UnprotectedRoute[];
    readonly client: TelzioClient;

    constructor(options: TelzioOptions = {}) {
        this._options = options;
        this._unprotectedRoutes = unprotectedRoutes();

        const _client = createClient<paths>({
            baseUrl: Telzio._baseUrl,
        });

        // add auth middleware
        const onRequestCallback: MiddlewareOnRequest = async ({ request, schemaPath }) => {
            const unprotected = this._unprotectedRoutes.some((route) => {
                return route.path == schemaPath
                    && route.method == request.method.toLowerCase();
            });

            if (unprotected) {
                return undefined;
            }

            if (this._options.apiKey) {
                // append API token
                request.headers.set(
                    'Authorization',
                    `Bearer ${this._options.apiKey}`
                );
            }

            return request;
        };
        const authMiddleware: Middleware = {
            onRequest: onRequestCallback,
        };

        this.client = wrapAsPathBasedClient(_client);
        _client.use(authMiddleware);
    }

    /**
     * Telzio sends Webhook JSON body data in the form of raw bytes which must be converted to a string, then parsed to JSON.
     * @param {Buffer} rawBody Raw body data received from Telzio.
     * @returns {WebhookEventBody} The body of a Webhook event.
     */
    public static jsonDataFromBodyBuffer(rawBody: Buffer): WebhookEventBody {
        return JSON.parse(rawBody.toString('utf-8'));
    }

    // TODO: figure out some way to add functions from operationIds
    // TODO: add static functions that don't require auth

    setAPIKey(key: string) {
        this._options.apiKey = key;
    }

    clearAPIKey() {
        this._options.apiKey = undefined;
    }
}
